from ubuntu:18.04

workdir ~
copy gem5 gem5
copy nvmain nvmain
run apt-get update && apt-get -y install build-essential git m4 scons zlib1g zlib1g-dev libprotobuf-dev protobuf-compiler libprotoc-dev libgoogle-perftools-dev python3-dev python3-six python libboost-all-dev pkg-config curl git
